name: AntiFarm
version: ${project.version}
description: This plugin prevents the use and abuse of mob farms.
author: Glitchfinder 
website: https://github.com/Glitchfinder/AntiFarm

main: org.antifarm.AntiFarm
